spring.application.name=goxu

# core
spring.profiles.active=mysql

# base end-points config
api-endpoint=/api

# Docker
spring.docker.compose.enabled=true

# Crea y actualiza las tablas desde las entidades al arrancar.
spring.jpa.hibernate.ddl-auto=update

# Muestra en consola el SQL que ejecuta Hibernate 
spring.jpa.show-sql=true

