# url de conexión a sql
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_p5
# user
spring.datasource.username=myuser
spring.datasource.password=verysecret
# driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# tablas CORRECCIÓN: create-drop to update
spring.jpa.hibernate.ddl-auto=update
# demora en ejecución
spring.jpa.defer-datasource-initialization=true
#sql en consola
spring.jpa.show-sql: true
# fuerza scrips de incialización
spring.sql.init.mode=always