# url de conexión
spring.datasource.url=jdbc:h2:mem:testdb

# driver que traduce entre Java y base de datos
spring.datasource.driver-class-name=org.h2.Driver

# CAMBIO
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# indica a Hibernate que genere SQL en H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# retrasa la carga de sql hasta después de que hibernate cree las tablas
spring.jpa.defer-datasource-initialization=true

# crea las tablas al arrancar (y borra al cerrar x H2)
spring.jpa.hibernate.ddl-auto=create-drop

# muestra la consola de sql que ejecuta Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# niveles de log
logging.level.root=warn
logging.level.org.springframework.web=debug
logging.level.org.hibernate=error


