INSERT INTO roles (name) SELECT 'CUSTOMER' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'CUSTOMER');
INSERT INTO roles (name) SELECT 'KITCHEN' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'KITCHEN');
INSERT INTO roles (name) SELECT 'DELIVERY' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'DELIVERY');
INSERT INTO roles (name) SELECT 'ADMIN' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ADMIN');

INSERT INTO events (title, description, event_date, image, details, price, featured) SELECT 'Cena Maridaje: Sidras de Espalme & Cortes Nobles', 'Un recorrido por 6 llagares históricos guiado por nuestra sumiller María Fernández, maridando cada paso con piezas singulares de goxu asturiano a baja temperatura.', '2026-10-17 20:30:00', '/events-img/events-pairing.jpeg', '18 plazas exclusivas', 75.00, TRUE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Cena Maridaje: Sidras de Espalme & Cortes Nobles');
INSERT INTO events (title, description, event_date, image, details, price, featured) SELECT 'Jornadas Gastronómicas del Chosco y la Carrillera', 'Tres días dedicados a la reinterpretación de dos grandes pilares de la cocina de montaña. Recetas tradicionales encontrándose con técnicas moleculares y texturas crujientes.', '2026-11-07 14:00:00', '/events-img/events-asturian-cured-pork-sausage.jpeg', 'Menú degustación 5 pases', 48.00, TRUE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Jornadas Gastronómicas del Chosco y la Carrillera');
INSERT INTO events (title, description, event_date, image, details, price, featured) SELECT 'Mesa Redonda: De la Dehesa al plato', 'Diálogo abierto entre criadores de goxu asturcelta, llagareros artesanales y nuestro equipo de cocina sobre la preservación de razas autóctonas y sostenibilidad rural.', '2026-11-26 19:00:00', '/events-img/events-panel-discussion.jpeg', 'Coloquio & Cóctel de cierre', NULL, TRUE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Mesa Redonda: De la Dehesa al plato');
INSERT INTO events (title, description, event_date, image, details, price, featured) SELECT 'Noche de Sidra Bajo las Estrellas', 'Cena al aire libre en nuestra terraza, con escanciado tradicional y música en directo de gaita asturiana.', '2027-06-15 21:00:00', '/events-img/events-pairing.jpeg', 'Terraza exterior', 55.00, FALSE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Noche de Sidra Bajo las Estrellas');
INSERT INTO events (title, description, event_date, image, details, price, featured) SELECT 'Vendimia y Sidra: Fiesta de la Cosecha', 'Celebración del cierre de temporada con productos de proximidad y una selección especial de sidras de la casa.', '2027-09-20 20:00:00', '/events-img/events-asturian-cured-pork-sausage.jpeg', 'Aforo limitado', 60.00, FALSE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Vendimia y Sidra: Fiesta de la Cosecha');

/*
  PRODUCTOS (CARTA)
  Mismo patrón que roles, eventos y ofertas: INSERT ... SELECT ... FROM DUAL WHERE NOT EXISTS.
  Así el script se puede ejecutar en cada arranque sin duplicar platos.
  - La comprobación de "ya existe" se hace por el nombre del plato.
  - image apunta a la carpeta public/menu-img/ del front (nombres sin tildes).
  - category usa exactamente las mismas palabras que las pestañas de CartaView.
  - badge_label y badge_tone quedan a NULL en los platos sin etiqueta.
  - Las comillas simples dentro de un texto se escriben dobles ('') para que SQL no crea que el texto termina ahí.
*/

/* ENTRANTES */
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Croquetas de compango', 'Cremosas, receta casera.', 8.50, '/menu-img/croquetas_de_compango.png', 'Entrantes', TRUE, TRUE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Croquetas de compango');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Chorizo a la sidra', 'Cocinado lentamente en sidra natural.', 9.00, '/menu-img/chorizo_a_la_sidra.png', 'Entrantes', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Chorizo a la sidra');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Tabla de embutidos asturianos', 'Chorizo, morcilla y jamón curado.', 14.00, '/menu-img/tabla_de_embutidos_asturianos.png', 'Entrantes', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Tabla de embutidos asturianos');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Callos a la asturiana', 'Guiso tradicional con garbanzos.', 10.50, '/menu-img/callos_a_la_asturiana.png', 'Entrantes', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Callos a la asturiana');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Croquetas de queso Cabrales', 'Sobre crema de manzana asturiana.', 9.00, '/menu-img/croquetas_de_queso_cabrales.png', 'Entrantes', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Croquetas de queso Cabrales');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Ensalada de la casa', 'Afuega''l Pitu, nueces y miel.', 8.00, '/menu-img/ensalada_de_la_casa.png', 'Entrantes', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Ensalada de la casa');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Picadillo casero', 'Con pan de hogaza tostado.', 8.50, '/menu-img/picadillo_casero.png', 'Entrantes', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Picadillo casero');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Pixín rebozado', 'Rape rebozado con alioli suave.', 11.00, '/menu-img/pixin_rebozado.png', 'Entrantes', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Pixín rebozado');

/* ESPECIALIDADES */
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Fabada asturiana con compango', 'La receta de siempre.', 16.00, '/menu-img/fabada.png', 'Especialidades', TRUE, TRUE, 'Clásico', 'highlight' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Fabada asturiana con compango');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Cachopo Goxu', 'Jamón serrano y queso, empanado.', 19.50, '/menu-img/cachopo.png', 'Especialidades', TRUE, TRUE, 'Recomendado', 'primary' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Cachopo Goxu');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Costillar de cerdo a la sidra', 'Asado lento, glaseado en sidra.', 17.00, '/menu-img/costillar_asado.png', 'Especialidades', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Costillar de cerdo a la sidra');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Lacón con grelos', 'Con patata y chorizo.', 15.50, '/menu-img/lacon_con_grelos.png', 'Especialidades', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Lacón con grelos');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Panceta confitada con manzana', 'Panceta de cerdo asturiano.', 16.50, '/menu-img/panceta_glaseada.png', 'Especialidades', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Panceta confitada con manzana');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Chuletón de cerdo a la brasa', 'Cerdo ibérico a la brasa.', 18.00, '/menu-img/chuleton_cerdo.png', 'Especialidades', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Chuletón de cerdo a la brasa');

/* CARNES */
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Carrillera de ternera al vino', 'Guisada a fuego lento en vino tinto hasta quedar melosa.', 17.50, '/menu-img/carrillera_de_ternera_al_vino.png', 'Carnes', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Carrillera de ternera al vino');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Chuletón de vaca asturiana', 'Madurado y hecho a la brasa, con patatas y pimientos.', 26.00, '/menu-img/chuleton_de_vaca_asturiana.png', 'Carnes', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Chuletón de vaca asturiana');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Entrecot a la brasa', 'Con sal en escamas y guarnición de temporada.', 21.00, '/menu-img/entrecot_a_la_brasa.png', 'Carnes', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Entrecot a la brasa');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Pitu de caleya guisado', 'Pollo de corral guisado a la manera tradicional.', 19.00, '/menu-img/pitu_de_caleya_guisado.png', 'Carnes', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Pitu de caleya guisado');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Solomillo de ternera asturiana', 'A la plancha, con salsa de queso Cabrales.', 24.00, '/menu-img/solomillo_de_ternera_asturiana.png', 'Carnes', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Solomillo de ternera asturiana');

/* PESCADOS */
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Pixín a la marinera', 'Rape en salsa marinera con almejas.', 20.00, '/menu-img/pixin_a_la_marinera.png', 'Pescados', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Pixín a la marinera');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Bacalao a la asturiana', 'Con salsa de sidra y patatas panaderas.', 18.50, '/menu-img/bacalao_a_la_asturiana.png', 'Pescados', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Bacalao a la asturiana');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Merluza a la sidra', 'Merluza del Cantábrico en salsa de sidra natural.', 19.00, '/menu-img/merluza_a_la_sidra.png', 'Pescados', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Merluza a la sidra');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Rodaballo a la plancha', 'Con verduras de temporada y aceite de oliva.', 22.00, '/menu-img/rodaballo_a_la_plancha.png', 'Pescados', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Rodaballo a la plancha');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Salmón a la parrilla', 'Con guarnición de patata asada y ensalada.', 17.00, '/menu-img/salmon_a_la_parrilla.png', 'Pescados', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Salmón a la parrilla');

/* POSTRES */
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Compota de manzana', 'Manzana asturiana cocinada lentamente con canela.', 5.00, '/menu-img/compota_manzana.png', 'Postres', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Compota de manzana');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Carbayones', 'El dulce de Oviedo, de hojaldre y almendra.', 5.50, '/menu-img/carbayones.png', 'Postres', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Carbayones');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Tarta de queso', 'Cremosa, con un ligero toque caramelizado.', 6.50, '/menu-img/tarta_de_queso.png', 'Postres', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Tarta de queso');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Frixuelos con miel', 'Finos y dorados, con miel de la tierra.', 5.50, '/menu-img/frixuelos_con_miel.png', 'Postres', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Frixuelos con miel');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Casadielles', 'Rellenas de nuez y anís, receta tradicional.', 5.50, '/menu-img/casadielles.png', 'Postres', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Casadielles');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Arroz con leche', 'Cremoso y requemado al momento.', 5.50, '/menu-img/arroz_con_leche.png', 'Postres', TRUE, TRUE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Arroz con leche');

/* BEBIDAS */
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Refrescos', 'Selección de refrescos.', 2.50, '/menu-img/refrescos.png', 'Bebidas', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Refrescos');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Infusiones', 'Té e infusiones variadas.', 2.00, '/menu-img/infusiones.png', 'Bebidas', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Infusiones');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Cerveza artesanal asturiana', 'Elaborada en Asturias, botellín de 33 cl.', 4.00, '/menu-img/cerveza_artesanal_asturiana.png', 'Bebidas', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Cerveza artesanal asturiana');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Vino tinto DO', 'Botella de vino tinto con denominación de origen.', 18.00, '/menu-img/vino_tinto_do.png', 'Bebidas', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Vino tinto DO');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Vino blanco DO', 'Botella de vino blanco con denominación de origen.', 16.00, '/menu-img/vino_blanco_do.png', 'Bebidas', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Vino blanco DO');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Sidra de hielo', 'Sidra dulce asturiana, ideal con el postre. Copa.', 6.00, '/menu-img/sidra_de_hielo.png', 'Bebidas', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Sidra de hielo');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Botella de sidra', 'Sidra natural asturiana, escanciada en mesa.', 4.50, '/menu-img/botella_sidra.png', 'Bebidas', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Botella de sidra');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Agua Fuensanta', 'Agua mineral asturiana.', 2.00, '/menu-img/agua_fuensanta.png', 'Bebidas', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Agua Fuensanta');

INSERT INTO offers (title, description, image, badge, price, featured) SELECT 'Menú Degustación ''Mar y Montaña''', 'Disfrute de un menú degustación de 8 pasos con el verdadero sabor asturiano. Una propuesta exclusiva para nuestros mejores clientes, acompañada por el maridaje de la casa.', '/offers-img/menu_degustacion.png', 'Exclusivo para miembros', 85.00, TRUE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM offers WHERE title = 'Menú Degustación ''Mar y Montaña''');
INSERT INTO offers (title, description, image, badge, price, featured) SELECT 'Maridaje de Autor Sin Costo', 'Disfrute de una botella seleccionada de nuestra bodega privada al reservar mesa para cenar los jueves.', '/menu-img/vino_tinto_do.png', 'Hasta el Jueves', NULL, FALSE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM offers WHERE title = 'Maridaje de Autor Sin Costo');
UPDATE offers SET image = '/menu-img/vino_tinto_do.png' WHERE title = 'Maridaje de Autor Sin Costo';
INSERT INTO offers (title, description, image, badge, price, featured) SELECT 'Dulce Celebración', 'Un postre artesanal de cortesía y brindis con cava para usted y sus invitados en el mes de su cumpleaños.', '/offers-img/dulce_celebracion.png', 'Cumpleaños', NULL, FALSE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM offers WHERE title = 'Dulce Celebración');
INSERT INTO offers (title, description, image, badge, price, featured) SELECT 'Masterclass Gastronómica', 'Acceso prioritario y descuento especial para nuestra próxima sesión íntima con nuestro Chef Ejecutivo.', '/offers-img/master_class.png', 'Solo Miembros VIP', NULL, FALSE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM offers WHERE title = 'Masterclass Gastronómica');

INSERT INTO users (name, email, password) SELECT 'Administrador', 'admin@goxu.com',    '$2a$10$Rl2n.OWDJKfwFWCrQogZ7.E9ym5kO0oWYGDhKaS28MisEzc.ftNeq' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'admin@goxu.com');
INSERT INTO users (name, email, password) SELECT 'Cocina',        'kitchen@goxu.com',  '$2a$10$RUvPWk3ovbxyQXWO1m.KSOdRio8Q5xzARP279BFI4itxKxaRt41zy' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'kitchen@goxu.com');
INSERT INTO users (name, email, password) SELECT 'Repartidor',    'delivery@goxu.com', '$2a$10$5PTSKNhP18hayKVkzWLh2e/gEMOedSSVvrZ/pydonCLLsZMeemgXy' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'delivery@goxu.com');

INSERT INTO roles_users (user_id, role_id) SELECT u.id_user, r.id_role FROM users u, roles r WHERE u.email = 'admin@goxu.com'    AND r.name = 'ADMIN'    AND NOT EXISTS (SELECT 1 FROM roles_users ru WHERE ru.user_id = u.id_user AND ru.role_id = r.id_role);
INSERT INTO roles_users (user_id, role_id) SELECT u.id_user, r.id_role FROM users u, roles r WHERE u.email = 'kitchen@goxu.com'  AND r.name = 'KITCHEN'  AND NOT EXISTS (SELECT 1 FROM roles_users ru WHERE ru.user_id = u.id_user AND ru.role_id = r.id_role);
INSERT INTO roles_users (user_id, role_id) SELECT u.id_user, r.id_role FROM users u, roles r WHERE u.email = 'delivery@goxu.com' AND r.name = 'DELIVERY' AND NOT EXISTS (SELECT 1 FROM roles_users ru WHERE ru.user_id = u.id_user AND ru.role_id = r.id_role);