INSERT INTO roles (name) SELECT 'CUSTOMER' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'CUSTOMER');
INSERT INTO roles (name) SELECT 'KITCHEN' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'KITCHEN');
INSERT INTO roles (name) SELECT 'DELIVERY' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'DELIVERY');
INSERT INTO roles (name) SELECT 'ADMIN' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ADMIN');

