INSERT INTO roles (name) SELECT 'CUSTOMER' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'CUSTOMER');
INSERT INTO roles (name) SELECT 'KITCHEN' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'KITCHEN');
INSERT INTO roles (name) SELECT 'DELIVERY' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'DELIVERY');
INSERT INTO roles (name) SELECT 'ADMIN' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ADMIN');

INSERT INTO events (title, description, event_date, image, details, price, featured) SELECT 'Cena Maridaje: Sidras de Espalme & Cortes Nobles', 'Un recorrido por 6 llagares históricos guiado por nuestra sumiller María Fernández, maridando cada paso con piezas singulares de goxu asturiano a baja temperatura.', '2026-03-28 20:30:00', '/events-img/events-pairing.jpeg', '18 plazas exclusivas', 75.00, TRUE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Cena Maridaje: Sidras de Espalme & Cortes Nobles');
INSERT INTO events (title, description, event_date, image, details, price, featured) SELECT 'Jornadas Gastronómicas del Chosco y la Carrillera', 'Tres días dedicados a la reinterpretación de dos grandes pilares de la cocina de montaña. Recetas tradicionales encontrándose con técnicas moleculares y texturas crujientes.', '2026-11-07 14:00:00', '/events-img/events-asturian-cured-pork-sausage.jpeg', 'Menú degustación 5 pases', 48.00, TRUE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Jornadas Gastronómicas del Chosco y la Carrillera');
INSERT INTO events (title, description, event_date, image, details, price, featured) SELECT 'Mesa Redonda: De la Dehesa al plato', 'Diálogo abierto entre criadores de goxu asturcelta, llagareros artesanales y nuestro equipo de cocina sobre la preservación de razas autóctonas y sostenibilidad rural.', '2026-11-26 19:00:00', '/events-img/events-panel-discussion.jpeg', 'Coloquio & Cóctel de cierre', NULL, TRUE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Mesa Redonda: De la Dehesa al plato');
INSERT INTO events (title, description, event_date, image, details, price, featured) SELECT 'Noche de Sidra Bajo las Estrellas', 'Cena al aire libre en nuestra terraza, con escanciado tradicional y música en directo de gaita asturiana.', '2027-06-15 21:00:00', '/events-img/events-pairing.jpeg', 'Terraza exterior', 55.00, FALSE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Noche de Sidra Bajo las Estrellas');
INSERT INTO events (title, description, event_date, image, details, price, featured) SELECT 'Vendimia y Sidra: Fiesta de la Cosecha', 'Celebración del cierre de temporada con productos de proximidad y una selección especial de sidras de la casa.', '2027-09-20 20:00:00', '/events-img/events-asturian-cured-pork-sausage.jpeg', 'Aforo limitado', 60.00, FALSE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Vendimia y Sidra: Fiesta de la Cosecha');
